version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  server:
