export const READ_PERMISSION = 'R';
export const WRITE_PERMISSION = 'W';
export const UPDATE_PERMISSION = 'U';
export const DELETE_PERMISSION = 'D';
export const APPROVE_PERMISSION = 'A';

export const READ_FORM_PERMISSION = 'RF';
export const WRITE_FORM_PERMISSION = 'WF';
export const UPDATE_FORM_PERMISSION = 'UF';
export const DELETE_FORM_PERMISSION = 'DF';
export const APPROVE_FORM_PERMISSION = 'AF';

export const EMPLOYEE_FORM_STATUS_NEW = 'NEW';
export const EMPLOYEE_FORM_STATUS_APPROVED = 'APPROVED';
export const EMPLOYEE_FORM_STATUS_SUBMITTED = 'SUBMITTED';
export const EMPLOYEE_FORM_STATUS_REJECTED = 'REJECTED';
export const EMPLOYEE_FORM_STATUS_CLOSED = 'CLOSED';

export const FORM_STATUS_NEW = 'NEW';
export const FORM_STATUS_CLOSED = 'CLOSED';
export const FORM_STATUS_DELETED = 'DELETED';
